 # =====ParaCtl:是否输出默认控制参数========
 # OutputAllPara:not Equal 0,OutPut All Control para
 # ==================================
 &PARACTL
 OUTPUTALLPARA   = 1
 /

# Rundef:运行参数
# startType:startup:Cold Start 0;
#     hybrid:restart Use Data Only;
#     branch:restart Change Case;
#     continue: restart;
# caseid   :caseName
# pathinit :Init File Directory
# pathrest :restart File Directory
# pathhist :History File Directory
# pathloc  :History File Local Directory
# pathwind :Wind Data Directory
# pathcur  :Cur  Data Directory
# topofn   :topography File
# topofType:topography File Type 1:text,3:NetCdf
# DEPTHMOD : 0
# DBGLVL   :Debug level
# RUNDAYS  :RUNDAYS
# StartDate:StartDate
# StartTime:StartTime
# PreCalTime:Define PreCal Time in hour
 &RUNDEF
 STARTTYPE  = "startup",
 CASEID     = "test",
 PATHINIT   = "init/",
 PATHREST   = "rest/",
 PATHHIST   = "hist/",
 PATHLOC    = "/tmp/",
 PATHCUR    = "cur/",
 TOPOFN     = "init/etop5.nc",
 TOPOFTYPE  = 3, !
 DEPTHMOD   = 1, !
 DBGLVL     =   14,
 STARTDATE  = 20080101,
 STARTTIME  = 000000,
 PRECALTIME =   0.,
 RUNDAYS    = 3,
 OUTPUTNEP  = 0,
 OUTTYPE    = 0
/
# PATHWIND   = "wind",
# UFNFORM    = '%P/uwnd.sig995.%4.4Y.nc',
# UWIND_NAME = "uwnd",
# VFNFORM    = '%P/vwnd.sig995.%4.4Y.nc',
# VWIND_NAME = "vwnd" ,

# UFNFORM    = '%P/wind%4.4Y%2.2M.nc'
# UWIND_NAME = "windu",
# VFNFORM    = '%P/wind%4.4Y%2.2M.nc'
# VWIND_NAME = "windv" ,

&WINDFORM
 PATHWIND   = "wind",
 UFNFORM    = '%P/uwnd.sig995.%4.4Y.nc',
 UWIND_NAME = "uwnd",
 VFNFORM    = '%P/vwnd.sig995.%4.4Y.nc',
 VWIND_NAME = "vwnd" ,
 WTIME_PATCH=-2
/

 # ===========GPARA: 全局参数=========
 # (gxlon0-gxlon1,gylat0-gylat1):计算区域
 # deltts:时间步长(s),ngpd:每度网格数
 # 1deg:1h/3,0.5deg:1h/5,1/4deg:1h/10(1h/9不行)
 # 1/8:1h/20 1/20: 1/50 
 # 1/60:20 0.0166666666667
 # Gcircle:全球模式,环绕
 # logscurr:THE SWITCH FOR WAVE-CURRENT INTERACTION
 # logsdiss:THE SWITCH FOR Sds,1-Yuan's,0-Komen's
 # ==================================
 &GPARA
 DELTTS  =    12.0000    ,
 GXLON0  =  -180.0000    ,
 GYLAT0  =   -60.0000    ,
 GXLON1  =   180.0000    ,
 GYLAT1  =    60.0000    ,
 GRDSZX  =     0.01      ,
 GRDSZY  =     0.01      ,
 GCIRCLE =   1,
 windfield = 200,
 LOGSCURR  = 0,
 LOGSDISS  = 0
 /

 # BVDepDef:bv layer define
 # ndep :BV N layers
 # vdep :bv layers
 &BVDEPDEF
 NDEP    =    40,
 VDEP    = 0,2.5,  5,7.5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100,110,120,130,140,150,160,170,180,190,200,225,250,275,300,325,350,375, 400,450,500,750,1000,120*0.
 /
 #NDEP    =    31,
 #VDEP    = 4.999938, 15.00029, 25.00176, 35.00541, 45.01332, 55.0295, 65.06181, 75.12551, 85.25037, 95.49429, 105.9699, 116.8962, 128.6979, 142.1953, 158.9606, 181.9628, 216.6479, 272.4767, 364.303, 511.5348, 732.2009, 1033.217, 1405.698, 1830.885, 2289.768, 2768.242, 3257.479, 3752.442, 4250.401, 4749.913, 5250.227 ,129*0.

 # OUTdef:输出参数
 # AVHIST_OPTIONS,AVHIST_NS:
 # REST_OPTION,REST_N:
 #   "AUTO":use CPL Control;"NONE","NEVER":Not Output;
 #   "NSTEPS":N Steps;"NHOURS: N Hours;"NDAYS":N Days;"NMONTHS":N months;"NYEARS":N Years
 #   "daily": 1day;"monthly":1 month,"yearly":1 year
 #   if(N<0):Mean OutPut not Average,transient field
 # HIST_NTPF,AVHIST_NTPFS :每文件输出次数,>0: n Times;
 #    0: 1 day;
 #   -1: 1 month;
 #   -2: 1 Season;
 #   -3: half year: 
 #  <-3: -n-4 year 
 # AVHIST_OTAGS: OutName Tag,default:"ahi"
 # AVHIST_TAGS,AVHIST_OPTION,AVHIST_NS,AVHIST_NTPFS:is array surport Multi(max 16) Output
 &OUTDEF
 REST_OPTION = "NMONTH  ",
 REST_N = 1,
 AVHIST_OTAGS = "h",15*" ",
 AVHIST_OPTIONS ="NHOURS",15*"NONE",
 AVHIST_NS = 1,15*24,
 AVHIST_NTPFS =-4, 15*-1,
 LOGBVS   = 6,0,14*0,
 LOGWINDS = 6,0,14*0,
 LOGHSS   = 6,0,14*0,
 LOGTPS   = 6,0,14*0,
 LOGTZS   = 6,0,14*0,
 LOGTHS   = 6,0,14*0,
 LOGAUS   = 16*0
 /
 # =====implschPara:源函数系数========
 # beta0,beta1:WIND INPUT COEFFICIENT
 # brkd1,brkd2:WIND INPUT COEFFICIENT
 # acu:Current COEFFICIENT
 # ==================================
 &IMPLSCHPARA
 BETA0   =   1.000000    ,
 BETA1   =  0.0000000E+00,
 ACU     =   1.000000    ,
 BRKD1   =  1.3200000E-04,
 BRKD2   =   2.610000
 /

 # PKPARA:波束划分参数
 # KL波束划分数 ,kld,总波束划分数,jnthet 方向划分数
 # wk(k)=wkmin*(pwk**(k-1))
 &PKPARA
 PWK     =   1.210000    ,
 WKMIN   =  7.1000000E-03,
 KL      =    32,
 KLD     =    32,
 JNTHET  =    12
 /

 # 测试选项
 &TESTOPT
 iCheckRestart = 0 ,
 noOutPut      = 1 ,
 constwindx    = 0 ,
 constwindy    = 0
 /
# PLO    =   84.0514 ,
# PLA    =   -46.09333
 # OUTPUTPnt:监测/工作点坐标
 &OUTPUTPNT
 PLO    = 140 ,15*1000,
 PLA    = 30 ,15*1000
 /

 #======== CPLDEF:CCSM 耦合参数'========
 # NCPL :每天耦合次数'
 # ==================================
 &CPLDEF
 NCPL=1
 /
 # 系统参数
 # NCorePClu  :每簇(NUMA)核数(38)
 # MCorePClu  ;每簇(NUMA)可用核数(38),假设不可用核在最后
 # NCluPNode  :每节点簇数(16)
 # NManageCore;管理核核数，编号>NCorePClu*NCluPNode
 # 软件设置参数
 # NThPGrp :每组启动线程数(38),2<=NProcPNode<=MCorePClu
 # NGrpPProc:每进程组数(16),<=NCluPNode ,支持 4,8,16,
 # NProcPNode:每节点进程数(1),<=NCluPNode/NGrpPProc
 # ManageCoreId:管理核(-1)
 # 测试用参数
 # OffClu   :第一组使用的簇(0)
 # SkipClu  :几个簇启动1个组间(1)
 # OffCore  :每个组使用的第一个核(0)
 # SkipCore :几个核启动一个线程(1)
 &THEADSEF
 NCorePClu    =   38,
 MCorePClu    =   37,
 NCluPNode    =   16,
 NManageCore  =    0,
 NGrpPProc    =   16,
 NThPGrp      =   36,
 NProcPNode   =    1,
 ManageCoreid =   -1,
 OffClu       =    0,
 SkipClu      =    1,
 OffCore      =    0,
 SkipCore     =    1
 /
